-- This file has been generated by /nix/store/5j7b8wmy6h32cb98b59dhpz00xm35g68-notion-3-2017050501/bin/notion. Do not edit.
return {
    [0] = {
        ["managed"] = {
            [1] = {
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["geom"] = {
                            ["w"] = 1280,
                            ["x"] = 0,
                            ["y"] = 0,
                            ["h"] = 800,
                        },
                        ["split_tree"] = {
                            ["dir"] = "horizontal",
                            ["tl"] = {
                                ["dir"] = "vertical",
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                            [1] = {
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 1,
                                                        ["geom"] = {
                                                            ["w"] = 640,
                                                            ["x"] = 0,
                                                            ["y"] = 0,
                                                            ["h"] = 763,
                                                        },
                                                        ["bottom"] = true,
                                                        ["windowid"] = 20971523,
                                                        ["level"] = 1,
                                                        ["type"] = "WClientWin",
                                                        ["sizepolicy"] = "full",
                                                    },
                                                },
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<1>",
                                                ["level"] = 0,
                                                ["switchto"] = true,
                                                ["geom"] = {
                                                    ["w"] = 640,
                                                    ["x"] = 1,
                                                    ["y"] = 21,
                                                    ["h"] = 763,
                                                },
                                                ["sizepolicy"] = "full",
                                            },
                                        },
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame",
                                        ["mode"] = 1,
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["tls"] = 785,
                                ["brs"] = 15,
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["tls"] = 642,
                            ["brs"] = 638,
                            ["br"] = {
                                ["dir"] = "vertical",
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                            [1] = {
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 2,
                                                        ["geom"] = {
                                                            ["w"] = 636,
                                                            ["x"] = 0,
                                                            ["y"] = 0,
                                                            ["h"] = 378,
                                                        },
                                                        ["bottom"] = true,
                                                        ["windowid"] = 23068675,
                                                        ["level"] = 1,
                                                        ["type"] = "WClientWin",
                                                        ["sizepolicy"] = "full",
                                                    },
                                                },
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<2>",
                                                ["level"] = 0,
                                                ["switchto"] = true,
                                                ["geom"] = {
                                                    ["w"] = 636,
                                                    ["x"] = 1,
                                                    ["y"] = 21,
                                                    ["h"] = 378,
                                                },
                                                ["sizepolicy"] = "full",
                                            },
                                        },
                                        ["type"] = "WFrame",
                                        ["name"] = "Tiling Frame<5>",
                                        ["mode"] = 1,
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["tls"] = 400,
                                ["brs"] = 400,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["type"] = "WFrame",
                                        ["name"] = "Tiling Frame",
                                        ["mode"] = 1,
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["type"] = "WSplitSplit",
                        },
                        ["sizepolicy"] = "full",
                    },
                },
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS",
                ["geom"] = {
                    ["w"] = 1280,
                    ["x"] = 0,
                    ["y"] = 0,
                    ["h"] = 800,
                },
                ["level"] = 0,
                ["switchto"] = true,
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["sizepolicy"] = "full",
            },
            [2] = {
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<3>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["geom"] = {
                            ["w"] = 1280,
                            ["x"] = 0,
                            ["y"] = 0,
                            ["h"] = 800,
                        },
                        ["split_tree"] = {
                            ["dir"] = "vertical",
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["checkcode"] = 3,
                                                    ["geom"] = {
                                                        ["w"] = 1278,
                                                        ["x"] = 0,
                                                        ["y"] = 0,
                                                        ["h"] = 763,
                                                    },
                                                    ["bottom"] = true,
                                                    ["windowid"] = 14680065,
                                                    ["level"] = 1,
                                                    ["type"] = "WClientWin",
                                                    ["sizepolicy"] = "full",
                                                },
                                            },
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW",
                                            ["level"] = 0,
                                            ["switchto"] = true,
                                            ["geom"] = {
                                                ["w"] = 1278,
                                                ["x"] = 1,
                                                ["y"] = 21,
                                                ["h"] = 763,
                                            },
                                            ["sizepolicy"] = "full",
                                        },
                                    },
                                    ["type"] = "WFrame",
                                    ["name"] = "Tiling Frame<10>",
                                    ["mode"] = 1,
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["tls"] = 785,
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                        ["sizepolicy"] = "full",
                    },
                },
                ["type"] = "WGroupWS",
                ["name"] = "www",
                ["hidden"] = true,
                ["level"] = 0,
                ["geom"] = {
                    ["w"] = 1280,
                    ["x"] = 0,
                    ["y"] = 0,
                    ["h"] = 800,
                },
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["sizepolicy"] = "full",
            },
            [3] = {
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<2>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["geom"] = {
                            ["w"] = 1280,
                            ["x"] = 0,
                            ["y"] = 0,
                            ["h"] = 800,
                        },
                        ["split_tree"] = {
                            ["dir"] = "horizontal",
                            ["tl"] = {
                                ["dir"] = "vertical",
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<1>",
                                        ["mode"] = 1,
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["tls"] = 785,
                                ["brs"] = 15,
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["tls"] = 640,
                            ["brs"] = 640,
                            ["br"] = {
                                ["dir"] = "vertical",
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<3>",
                                        ["mode"] = 1,
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["tls"] = 400,
                                ["brs"] = 400,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["type"] = "WFrame",
                                        ["name"] = "Tiling Frame<2>",
                                        ["mode"] = 1,
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["type"] = "WSplitSplit",
                        },
                        ["sizepolicy"] = "full",
                    },
                },
                ["type"] = "WGroupWS",
                ["name"] = "notion",
                ["hidden"] = true,
                ["level"] = 0,
                ["geom"] = {
                    ["w"] = 1280,
                    ["x"] = 0,
                    ["y"] = 0,
                    ["h"] = 800,
                },
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["sizepolicy"] = "full",
            },
            [4] = {
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<3>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["geom"] = {
                            ["w"] = 1280,
                            ["x"] = 0,
                            ["y"] = 0,
                            ["h"] = 800,
                        },
                        ["split_tree"] = {
                            ["dir"] = "vertical",
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["checkcode"] = 3,
                                                    ["geom"] = {
                                                        ["w"] = 1278,
                                                        ["x"] = 0,
                                                        ["y"] = 0,
                                                        ["h"] = 763,
                                                    },
                                                    ["bottom"] = true,
                                                    ["windowid"] = 14680065,
                                                    ["level"] = 1,
                                                    ["type"] = "WClientWin",
                                                    ["sizepolicy"] = "full",
                                                },
                                            },
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW",
                                            ["level"] = 0,
                                            ["switchto"] = true,
                                            ["geom"] = {
                                                ["w"] = 1278,
                                                ["x"] = 1,
                                                ["y"] = 21,
                                                ["h"] = 763,
                                            },
                                            ["sizepolicy"] = "full",
                                        },
                                    },
                                    ["type"] = "WFrame",
                                    ["name"] = "Tiling Frame<10>",
                                    ["mode"] = 1,
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["tls"] = 785,
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                        ["sizepolicy"] = "full",
                    },
                },
                ["type"] = "WGroupWS",
                ["name"] = "cad",
                ["hidden"] = true,
                ["level"] = 0,
                ["geom"] = {
                    ["w"] = 1280,
                    ["x"] = 0,
                    ["y"] = 0,
                    ["h"] = 800,
                },
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["sizepolicy"] = "full",
            },
            [5] = {
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<4>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["geom"] = {
                            ["w"] = 1280,
                            ["x"] = 0,
                            ["y"] = 0,
                            ["h"] = 800,
                        },
                        ["split_tree"] = {
                            ["dir"] = "vertical",
                            ["tl"] = {
                                ["dir"] = "horizontal",
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<6>",
                                        ["mode"] = 1,
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["tls"] = 806,
                                ["brs"] = 474,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["type"] = "WFrame",
                                        ["name"] = "Tiling Frame<6>",
                                        ["mode"] = 1,
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["tls"] = 629,
                            ["brs"] = 171,
                            ["br"] = {
                                ["dir"] = "horizontal",
                                ["tl"] = {
                                    ["dir"] = "vertical",
                                    ["tl"] = {
                                        ["regparams"] = {
                                            ["managed"] = {
                                            },
                                            ["type"] = "WFrame",
                                            ["name"] = "Tiling Frame<4>",
                                            ["mode"] = 1,
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["tls"] = 156,
                                    ["brs"] = 15,
                                    ["br"] = {
                                        ["type"] = "WSplitST",
                                    },
                                    ["type"] = "WSplitSplit",
                                },
                                ["tls"] = 637,
                                ["brs"] = 643,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["type"] = "WFrame",
                                        ["name"] = "Tiling Frame<3>",
                                        ["mode"] = 1,
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["type"] = "WSplitSplit",
                        },
                        ["sizepolicy"] = "full",
                    },
                },
                ["type"] = "WGroupWS",
                ["name"] = "vim",
                ["hidden"] = true,
                ["level"] = 0,
                ["geom"] = {
                    ["w"] = 1280,
                    ["x"] = 0,
                    ["y"] = 0,
                    ["h"] = 800,
                },
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["sizepolicy"] = "full",
            },
            [6] = {
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<5>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["geom"] = {
                            ["w"] = 1280,
                            ["x"] = 0,
                            ["y"] = 0,
                            ["h"] = 800,
                        },
                        ["split_tree"] = {
                            ["dir"] = "horizontal",
                            ["tl"] = {
                                ["dir"] = "vertical",
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<4>",
                                        ["mode"] = 1,
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["tls"] = 785,
                                ["brs"] = 15,
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["tls"] = 640,
                            ["brs"] = 640,
                            ["br"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                    },
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<5>",
                                    ["mode"] = 1,
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                        },
                        ["sizepolicy"] = "full",
                    },
                },
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<1>",
                ["hidden"] = true,
                ["level"] = 0,
                ["geom"] = {
                    ["w"] = 1280,
                    ["x"] = 0,
                    ["y"] = 0,
                    ["h"] = 800,
                },
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["sizepolicy"] = "full",
            },
            [7] = {
                ["managed"] = {
                    [1] = {
                        ["managed"] = {
                        },
                        ["mode"] = 0,
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["level"] = 1025,
                        ["geom"] = {
                            ["w"] = 640,
                            ["x"] = 320,
                            ["y"] = 160,
                            ["h"] = 480,
                        },
                        ["type"] = "WFrame",
                        ["sizepolicy"] = "free_glue",
                    },
                },
                ["name"] = "*scratchws*",
                ["hidden"] = true,
                ["pseudomodal"] = true,
                ["type"] = "WGroupWS",
                ["geom"] = {
                    ["w"] = 1280,
                    ["x"] = 0,
                    ["y"] = 0,
                    ["h"] = 800,
                },
                ["level"] = 1,
                ["unnumbered"] = true,
                ["initial_outputs"] = {
                },
                ["sizepolicy"] = "full",
            },
        },
        ["type"] = "WScreen",
        ["name"] = "WScreen",
    },
}

