# $Id: zshenv,v 1.7 2003/09/20 14:26:15 rasmusm Exp $

if [ -n "$DISPLAY" -o "$TERM" = "x10term" ]; then
    export TERM=xterm-color
fi
export EDITOR=vim              # name of your default editor
export PAGER=less                # name of your default pager
#export SHELL=zsh

# {{{ get local stuff... possibly overwrite
[[ -f ~/.zshenv-local ]] && source ~/.zshenv-local
# }}}
