-- This file has been generated by /nix/store/lhmz7mmqxiq4yn3992xbz3p8x7knbpxn-notion-4.0.0/bin/notion. Do not edit.
return {
    [0] = {
        ["type"] = "WScreen",
        ["name"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["geom"] = {
                    ["h"] = 800,
                    ["w"] = 1280,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["type"] = "WGroupWS",
                ["switchto"] = true,
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["dir"] = "horizontal",
                            ["tls"] = 641,
                            ["brs"] = 639,
                            ["type"] = "WSplitSplit",
                            ["br"] = {
                                ["dir"] = "vertical",
                                ["tls"] = 400,
                                ["brs"] = 400,
                                ["type"] = "WSplitSplit",
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "Tiling Frame",
                                        ["managed"] = {
                                            [1] = {
                                                ["geom"] = {
                                                    ["h"] = 378,
                                                    ["w"] = 637,
                                                    ["x"] = 1,
                                                    ["y"] = 21,
                                                },
                                                ["switchto"] = true,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["h"] = 378,
                                                            ["w"] = 637,
                                                            ["x"] = 0,
                                                            ["y"] = 0,
                                                        },
                                                        ["windowid"] = 8388611,
                                                        ["level"] = 0,
                                                        ["type"] = "WClientWin",
                                                        ["checkcode"] = 2,
                                                        ["sizepolicy"] = "full",
                                                    },
                                                },
                                                ["level"] = 0,
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "Tiling Frame<5>",
                                        ["managed"] = {
                                            [1] = {
                                                ["geom"] = {
                                                    ["h"] = 378,
                                                    ["w"] = 637,
                                                    ["x"] = 1,
                                                    ["y"] = 21,
                                                },
                                                ["switchto"] = true,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["h"] = 378,
                                                            ["w"] = 637,
                                                            ["x"] = 0,
                                                            ["y"] = 0,
                                                        },
                                                        ["windowid"] = 14680067,
                                                        ["level"] = 0,
                                                        ["type"] = "WClientWin",
                                                        ["checkcode"] = 1,
                                                        ["sizepolicy"] = "full",
                                                    },
                                                },
                                                ["level"] = 0,
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<1>",
                                                ["sizepolicy"] = "full",
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                            },
                            ["tl"] = {
                                ["dir"] = "vertical",
                                ["tls"] = 782,
                                ["brs"] = 18,
                                ["type"] = "WSplitSplit",
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                            },
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 800,
                            ["w"] = 1280,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["level"] = 0,
                        ["name"] = "WTiling",
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                    },
                },
                ["level"] = 0,
                ["name"] = "WGroupWS",
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["sizepolicy"] = "full",
            },
            [2] = {
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 800,
                    ["w"] = 1280,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 1,
                                ["type"] = "WFrame",
                                ["name"] = "Tiling Frame<10>",
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 800,
                            ["w"] = 1280,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["level"] = 0,
                        ["name"] = "WTiling<3>",
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                    },
                },
                ["level"] = 0,
                ["name"] = "www",
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["sizepolicy"] = "full",
            },
            [3] = {
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 800,
                    ["w"] = 1280,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["dir"] = "horizontal",
                            ["tls"] = 640,
                            ["brs"] = 640,
                            ["type"] = "WSplitSplit",
                            ["br"] = {
                                ["dir"] = "vertical",
                                ["tls"] = 400,
                                ["brs"] = 400,
                                ["type"] = "WSplitSplit",
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "Tiling Frame<2>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<3>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                            },
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<1>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 800,
                            ["w"] = 1280,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["level"] = 0,
                        ["name"] = "WTiling<2>",
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                    },
                },
                ["level"] = 0,
                ["name"] = "notion",
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["sizepolicy"] = "full",
            },
            [4] = {
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 800,
                    ["w"] = 1280,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 1,
                                ["saved_h"] = 785,
                                ["saved_x"] = 0,
                                ["managed"] = {
                                },
                                ["saved_y"] = 0,
                                ["name"] = "Tiling Frame<1>",
                                ["saved_w"] = 1280,
                                ["type"] = "WFrame",
                            },
                            ["type"] = "WSplitRegion",
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 800,
                            ["w"] = 1280,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["level"] = 0,
                        ["name"] = "WTiling<1>",
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                    },
                },
                ["level"] = 0,
                ["name"] = "cad",
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["sizepolicy"] = "full",
            },
            [5] = {
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 800,
                    ["w"] = 1280,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["dir"] = "vertical",
                            ["tls"] = 629,
                            ["brs"] = 171,
                            ["type"] = "WSplitSplit",
                            ["br"] = {
                                ["dir"] = "horizontal",
                                ["tls"] = 637,
                                ["brs"] = 643,
                                ["type"] = "WSplitSplit",
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "Tiling Frame<3>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "Tiling Frame<4>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                            },
                            ["tl"] = {
                                ["dir"] = "horizontal",
                                ["tls"] = 806,
                                ["brs"] = 474,
                                ["type"] = "WSplitSplit",
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "Tiling Frame<6>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<6>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                            },
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 800,
                            ["w"] = 1280,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["level"] = 0,
                        ["name"] = "WTiling<4>",
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                    },
                },
                ["level"] = 0,
                ["name"] = "vim",
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["sizepolicy"] = "full",
            },
            [6] = {
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 800,
                    ["w"] = 1280,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["dir"] = "horizontal",
                            ["tls"] = 640,
                            ["brs"] = 640,
                            ["type"] = "WSplitSplit",
                            ["br"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<5>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<4>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 800,
                            ["w"] = 1280,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["level"] = 0,
                        ["name"] = "WTiling<5>",
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                    },
                },
                ["level"] = 0,
                ["name"] = "WGroupWS<1>",
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["sizepolicy"] = "full",
            },
            [7] = {
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 800,
                    ["w"] = 1280,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["dir"] = "horizontal",
                            ["tls"] = 640,
                            ["brs"] = 640,
                            ["type"] = "WSplitSplit",
                            ["br"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<7>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<2>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 800,
                            ["w"] = 1280,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["level"] = 0,
                        ["name"] = "WTiling<6>",
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                    },
                },
                ["level"] = 0,
                ["name"] = "WGroupWS<2>",
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["sizepolicy"] = "full",
            },
            [8] = {
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 480,
                            ["w"] = 640,
                            ["x"] = 320,
                            ["y"] = 160,
                        },
                        ["managed"] = {
                        },
                        ["level"] = 1025,
                        ["name"] = "*scratchpad*",
                        ["type"] = "WFrame",
                        ["sizepolicy"] = "free_glue",
                    },
                },
                ["name"] = "*scratchws*",
                ["sizepolicy"] = "full",
                ["unnumbered"] = true,
                ["hidden"] = true,
                ["level"] = 1,
                ["initial_outputs"] = {
                },
                ["geom"] = {
                    ["h"] = 800,
                    ["w"] = 1280,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["type"] = "WGroupWS",
            },
        },
    },
}

